theme: jekyll-theme-tactile
title: Little Quotes Story
description: >-
  A data story on the quoting style of US news outlets.
baseurl: "/"
url: "https://naevyys.github.io/Little-quotes-story/"
group: "¿I did ADA did I?"